version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myliveapp
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  backend:
    build: ../backend
    command: npm run start:dev
    volumes:
      - ../backend:/app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/myliveapp
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
  admin:
    build: ../admin
    command: npm run dev -- --host
    volumes:
      - ../admin:/app
    ports:
      - '5173:5173'
    depends_on:
      - backend
  mobile:
    build: ../mobile
    command: npm run web
    volumes:
      - ../mobile:/app
    ports:
      - '8081:8081'
    depends_on:
      - backend
volumes:
  db_data:
  redis_data:
